gtkgui: Set save button not sensitive without images
Avoid the index error when clicking on the save button after all images
were removed:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/photocollage/gtkgui.py", line 401, in save_poster
    collage = self.history[self.history_index]
IndexError: list index out of range