gtkgui: Import urlib.parse instead of urllib
Because:

    >>> import urllib
    >>> urllib.parse.unquote('file://test')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'urllib' has no attribute 'parse'
    >>> import urllib.parse
    >>> urllib.parse.unquote('file://test')
    'file://test'

Closes https://github.com/adrienverge/PhotoCollage/issues/109